services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=taskManagerDB'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    restart: on-failure
